apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: store-front-hpa
  namespace: default  # Change namespace if store-front is deployed in a different one
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: store-front
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
